---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=260
  sha1: f8f086974d9769263078fb6cb7927655744dacbc
- name: bosh-openstack-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=27
  sha1: 85e6244978f775c888bbd303b874a2c158eb43c4

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent?v=3309
    sha1: 8dbfa43abf12e434707acf87a0a136977954e6e2
  cloud_properties:
    instance_type: m1.xlarge

disk_pools:
- name: disks
  disk_size: 20_000

networks:
- name: private
  type: manual
  subnets:
  - range: ((private_network_cidr)) # <--- Replace with a private subnet CIDR
    gateway: ((private_network_gateway)) # <--- Replace with a private subnet's gateway
    dns: ((private_network_dns)) # <--- Replace with your DNS
    cloud_properties: {net_id: ((private_network_uuid))} # <--- # Replace with private network UUID
- name: public
  type: vip

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: openstack_cpi, release: bosh-openstack-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [((private_bosh_ip))] # <--- Replace with a private IP
    default: [dns, gateway]
  - name: public
    static_ips: [((public_bosh_ip))] # <--- Replace with a floating IP

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    registry:
      address: ((private_bosh_ip)) # <--- Replace with a private IP
      host: ((private_bosh_ip)) # <--- Replace with a private IP
      db: *db
      http: {user: admin, password: admin, port: 25777}
      username: admin
      password: admin
      port: 25777

    blobstore:
      address: ((private_bosh_ip)) # <--- Replace with a private IP
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: openstack_cpi
      max_threads: 3
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}
      ssl:
        key: ((director_ssl_key))
        cert: ((director_ssl_cert))

    hm:
      director_account:
        user: hm
        password: hm-password
        ca_cert: ((director_ca_cert))
      resurrector_enabled: true

    openstack: &openstack
      auth_url: ((openstack_auth_url)) # <--- Replace with OpenStack Identity API endpoint
      project: ((openstack_project)) # <--- Replace with OpenStack project name
      domain: ((openstack_domain)) # <--- Replace with OpenStack domain name
      username: ((openstack_username)) # <--- Replace with OpenStack username
      api_key: ((openstack_password)) # <--- Replace with OpenStack password
      default_key_name: bosh
      default_security_groups: [bosh]

    agent: {mbus: "nats://nats:nats-password@((private_bosh_ip)):4222"} # <--- Replace with a private IP

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: openstack_cpi, release: bosh-openstack-cpi}

  ssh_tunnel:
    host: ((public_bosh_ip)) # <--- Replace with a floating IP
    port: 22
    user: vcap
    private_key: ./bosh.pem # Path relative to this manifest file

  mbus: "https://mbus:mbus-password@((public_bosh_ip)):6868" # <--- Replace with a floating IP

  properties:
    openstack: *openstack
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
